version: '3.8'

services:
  server:
    build: ./server
    environment:
      MONGODB_URI: ${MONGODB_URI}
      PI_API_KEY: ${PI_API_KEY}
      PI_API_SECRET: ${PI_API_SECRET}
    ports:
      - "3000:3000"
